
ALTER TABLE public.news_articles ADD COLUMN external_url TEXT DEFAULT NULL;

INSERT INTO public.news_articles (slug, date, iso_date, category, title, excerpt, content, external_url) VALUES
('kazoli-gouskou-corporate-governance-hub-2020', '23 July 2019', '2019-07-23', 'Publication', 'Δυναμική αρχή για την Corporate Governance Hub 2020', 'Elisavet Paspaliari wrote on MonoNews about the launch of Corporate Governance Hub 2020 by Xenia Kazoli and Angelika Gouskou.', '{}', 'https://www.mononews.gr/business/xenia-kazoli-ke-i-angelika-gkouskou-dinamiki-archi-gia-tin-corporate-governance-hub-2020'),
('selekos-emporiko-mitroo-gemi-anaptixiako', '19 September 2019', '2019-09-19', 'Publication', 'Το Εμπορικό Μητρώο (ΓΕΜΗ) καταργείται με την «απλοποίησή» του στο Αναπτυξιακό Πολυνομοσχέδιο', 'Petros Selekos wrote on MonoNews about the Commercial Registry (GEMI) and the Development Omnibus Bill.', '{}', 'https://www.mononews.gr/politics/columns-the-politic/p-selekos-to-emporiko-mitroo-gemi-katargite-me-tin-aplopiisi-tou-sto-anaptixiako-polinomoschedio'),
('selekos-thetika-arnitika-schediou-nomou-gemi', '07 May 2019', '2019-05-07', 'Publication', 'Τα θετικά και τα αρνητικά του Σχεδίου Νόμου για το Γ.Ε.ΜΗ', 'Petros Selekos wrote on MonoNews about the pros and cons of the Draft Law for GEMI.', '{}', 'https://www.mononews.gr/politics/columns-the-politic/petros-selekos-ta-thetika-ke-ta-arnitika-tou-schediou-nomou-gia-to-gemi'),
('gouskou-neos-nomos-ae-amoives-etairiki-diakyvernisi', '25 February 2019', '2019-02-25', 'Publication', 'Ο νέος νόμος για τις Α.Ε.: αμοιβές μελών Δ.Σ. και εταιρική διακυβέρνηση', 'Angelika Gouskou wrote on Kathimerini about the new law on S.A. companies, board member remuneration and corporate governance.', '{}', 'https://www.kathimerini.gr/economy/business/1011646/aggelika-a-gkoyskoy-o-neos-nomos-gia-tis-a-e-amoives-melon-d-s-kai-etairiki-diakyvernisi/'),
('gouskou-emporiki-diaitisia', '05 February 2017', '2017-02-05', 'Publication', 'Κυρίαρχος τρόπος επίλυσης διαφορών η εμπορική διαιτησία', 'Angelika Gouskou wrote on Kathimerini about commercial arbitration as the dominant method of dispute resolution.', '{}', 'https://www.kathimerini.gr/economy/local/894873/apopsi-kyriarchos-tropos-epilysis-diaforon-i-emporiki-diaitisia/');
